#!/bin/sh
# SPDX-FileCopyrightText: 2026 Fu Wenbo
# SPDX-License-Identifier: AGPL-3.0-or-later

[ -c /dev/ttyGS0 ] || exit 0

# The ACM function is created by S42. Keep this process in the background so
# the remaining system init scripts can continue.
/sbin/getty -L 115200 ttyGS0 vt100 &
