/* Automatically generated by p4c-wp4 from test_wp4.p4 on Thu Dec 10 15:00:42 2020
 */
#ifndef _P4_GEN_HEADER_
#define _P4_GEN_HEADER_

#define htonll(x) ((((uint64_t)htonl(x)) << 32) + htonl((x) >> 32))

#include <linux/types.h>

int wp4_packet_in(u8 *p_uc_data, u16 wp4_ul_size, u8 port);

struct wp4_input {
    u32 input_port; /* bit<32> */
};

struct wp4_output {
    u32 output_port; /* bit<32> */
};

struct rfFeatures_t {
    u64 timestamp; /* bit<64> */
    u16 rssi; /* bit<16> */
    u16 blank; /* bit<16> */
    u16 len; /* bit<16> */
    u16 rate_idx; /* bit<16> */
    u32 aux_1; /* bit<32> */
    s32 freqOffset; /* int<32> */
    u32 aux_3; /* bit<32> */
    u32 aux_4; /* bit<32> */
    u8 wp4_valid;
};

struct frameCtrl_t {
    u8 protoVer; /* bit<2> */
    u8 frameType; /* bit<2> */
    u8 subType; /* bit<4> */
    u8 toDS; /* bit<1> */
    u8 fromDS; /* bit<1> */
    u8 moreFrag; /* bit<1> */
    u8 retry; /* bit<1> */
    u8 pwrMgmt; /* bit<1> */
    u8 moreData; /* bit<1> */
    u8 protFrame; /* bit<1> */
    u8 order; /* bit<1> */
    u8 wp4_valid;
};

struct mac80211_t {
    u16 durID; /* bit<16> */
    u64 Addr1; /* macAddr_t */
    u64 Addr2; /* macAddr_t */
    u64 Addr3; /* macAddr_t */
    u16 seqCtrl; /* bit<16> */
    u64 Addr4; /* macAddr_t */
    u8 wp4_valid;
};

struct Headers_t {
    struct rfFeatures_t rfFeatures; /* rfFeatures_t */
    struct frameCtrl_t frameCtrl; /* frameCtrl_t */
    struct mac80211_t mac80211; /* mac80211_t */
};


#endif
